### ISSUE TITLE
Can I change English fonts? 

### ISSUE THREAD

**Issue by Frozty4628** [be5invis/Sarasa-Gothic#106]
Hi, I love this font pack, but iosvka just can't get my appetite. Can I change iosvka font to another font (like Consolas) and successfully compile?

**Comment by polarathene** [comment]
You could use an english font that you prefer, and try to influence this font as the fallback for Chinese/Japanese glyphs?(I am not sure if you can do that on Windows, but easy with Linux and I think macOS)

If you like Source Code Pro or Noto Sans Mono font, then you might like [Source Han Mono](https://github.com/adobe-fonts/source-han-mono)?

**Comment by he852100** [comment]
win有个东西叫字体链接。

**Comment by cwchien** [comment]
@he852100 This might be helpful.
[Font Technology - Globalization | Microsoft Docs](https://docs.microsoft.com/en-us/globalization/input/font-technology)

**Comment by PhoenixZeng** [comment]
@Frozty4628 有什么进展吗? 我也想换掉这个的英文字符

**Comment by Frozty4628** [comment]
> @Frozty4628 有什么进展吗? 我也想换掉这个的英文字符

我没再试了...第一是接受了这个英文字体，感觉其实蛮耐看，也清晰；第二是用字体编辑器换了英文字符的话，中英文就又不能对齐了，这实在是不能忍。我只知道Windows Terminal 能做到任意字体的中英文混输对齐。常用的VS、idea都不行，所以我决定不折腾了

**Comment by Lemmingh** [comment]
[我做到了](https://github.com/Lemmingh/Sarasa-Gothic/actions/runs/177853519)。**麻烦的是编译环境**。配置环境，尤其是 **otfcc**，花了大量时间。之前很多 issue 也是卡在外部依赖上。

我在 GitHub Actions 上实现，build 1 个已是 [GitHub-hosted runner](https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners) 的极限，再加就会超时。看上去，hinting 消耗了大部分时间。

## `.github/workflows/build.yml`

里面有很多为调试设计的日志。

```yaml
name: "Build"

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Artifact name"
        required: true
      type:
        description: "Build type (ttf/ttc)"
        required: true
        default: "ttf"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Log trigger info"
        shell: bash
        env:
          ARTIFACT_NAME: ${{ github.event.inputs.name }}
          BUILD_TYPE: ${{ github.event.inputs.type }}
        run: |
          echo "Actor: $GITHUB_ACTOR"
          echo "Event: $GITHUB_EVENT_NAME"
          echo
          echo "Commit: $GITHUB_SHA"
          echo "Branch: $GITHUB_REF"
          echo
          echo "Artifact: $ARTIFACT_NAME"
          echo "Build:    $BUILD_TYPE"

      - name: "Set environment variables `MY_BIN_PATH`, `PATH`"
        shell: pwsh
        run: |
          $myBinPath = "$env:HOME/bin"
          New-Item -Path $myBinPath -ItemType Directory
          Write-Output "::set-env name=MY_BIN_PATH::$myBinPath"
          Write-Output "::add-path::$myBinPath"

      - uses: actions/checkout@v2

      - name: "Setup Node.js environment"
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: "Setup Python environment"
        uses: actions/setup-python@v2
        with:
          python-version: "3"

      - name: "Install fonttools (latest)"
        shell: bash
        run: pip install fonttools

      - name: "Install Premake 5 (directly)"
        shell: bash
        run: |
          cd $MY_BIN_PATH
          wget -O - https://github.com/premake/premake-core/releases/download/v5.0.0-alpha15/premake-5.0.0-alpha15-linux.tar.gz | tar -xvz

      - name: "Checkout otfcc"
        uses: actions/checkout@v2
        with:
          repository: caryll/otfcc
          path: "otfcc"

      - name: "Install otfcc"
        shell: pwsh
        working-directory: "./otfcc"
        run: |
          premake5 gmake
          cd ./build/gmake
          make config=release_x64
          cd ../../bin/release-x64
          Copy-Item -Path '*' -Destination $env:MY_BIN_PATH -Recurse -PassThru
          ls -l $env:MY_BIN_PATH

      - name: "Install ttfautohint"
        shell: bash
        run: sudo apt --yes install ttfautohint

      - name: "Install AFDKO"
        shell: bash
        run: pip install afdko

      - name: "Install Node.js dependencies"
        shell: bash
        run: npm install

      - name: "Build fonts"
        shell: bash
        env:
          BUILD_TYPE: ${{ github.event.inputs.type }}
        run: npm run build $BUILD_TYPE

      - name: "(debug) Install tree"
        if: ${{ always() }}
        shell: bash
        run: sudo apt --yes install tree

      - name: "(debug) Log final workspace directory structure"
        if: ${{ always() }}
        shell: bash
        run: |
          tree -L 3

      - name: "(debug) Log environment variables"
        if: ${{ always() }}
        shell: pwsh
        run: |
          dir Env:
          echo "`nPATH::"
          $env:PATH -split ':'

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.name }}-${{ github.event.inputs.type }}
          path: "out/${{ github.event.inputs.type }}"

      - name: "(debug) Upload npm log"
        if: ${{ !success() }}
        uses: actions/upload-artifact@v2
        with:
          name: "npm-debug-log"
          path: "~/.npm/_logs"
```

## `sources/consolas/consolas-regular.ttf`

来自 Windows 10。

```yaml
Name: consolas-regular.ttf
Size: 459180 bytes (448 KiB)
CRC32: 472A19C9
CRC64: 1B6452E5FAFD7AAE
SHA256: C6E6CE8119FDD47EC6A5449A08E2D2AD7F41EA03143AAE193068ED9FA58EAEBC
SHA1: 2C3F9080C8EB055DA7AFD9C43CFC5FC5E9510DF6
BLAKE2sp: 9EAD8B8E98F2202BE8AAD36AF723F7DFCF49D71C181F07DBC9A77DB56E020DB9

Font name: Consolas
Version: 7.00
```

## `config.json`

> **注意**
>
> 一定要保证
>
> * `familyOrder` 与 `families`
> * `subfamilyOrder` 与 `subfamilies`
> * `styleOrder` 与 `styles`
>
> 中的项目一一对应，不要有多余。否则，生成文件的行为会很奇怪，出现了不需要的东西。
>
> 我琢磨了半天也没明白为什么。至少入口看上去挺正常…
> https://github.com/be5invis/Sarasa-Gothic/blob/79c43de7ddcc7f477d45139f36828794298f24d3/verdafile.js#L509-L518
> https://github.com/be5invis/Sarasa-Gothic/blob/79c43de7ddcc7f477d45139f36828794298f24d3/verdafile.js#L303-L324

我实现的是 **Sarasa Mono SC Regular**，西文换为 **Consolas**。于是：

```json
"familyOrder": ["mono-consolas"],
"families": {
  "mono-consolas": {
    "isMono": true,
    "isType": true,
    "latinGroup": "consolas",
    "naming": {
      "en_US": "Sarasa Mono Consolas",
      "zh_CN": "等距更纱黑体 Consolas",
      "zh_TW": "等距更紗黑體 Consolas",
      "zh_HK": "等距更紗黑體 Consolas",
      "ja_JP": "更紗等幅ゴシック Consolas",
      "ko_KR": "사라사 고정 폭고딕 Consolas"
    }
  }
}
```

```json
"subfamilyOrder": ["sc"],
"subfamilies": {
  "sc": {
    "name": "SC"
  }
}
```

```json
"styleOrder": [
  "regular"
],
"styles": {
  "regular": {
    "name": "Regular"
  }
}
```

产物没有明显问题，但 **Consolas** 提供的特性显然比 **Iosevka** 少，比如 **Consolas** 没有连字 (ligature)。

**Consolas** 是很简单的情况。对于更复杂的，参看 `latinGroups`，以及对 Source Han Sans 的处理（我没读懂）。

https://github.com/be5invis/Sarasa-Gothic/blob/79c43de7ddcc7f477d45139f36828794298f24d3/verdafile.js#L218-L236
https://github.com/be5invis/Sarasa-Gothic/blob/79c43de7ddcc7f477d45139f36828794298f24d3/verdafile.js#L110-L166
