### ISSUE TITLE
I want to build only Sarasa Term and Term Slab with Iosevka's buildPlans

### ISSUE THREAD

**Issue by gusbemacbe** [be5invis/Sarasa-Gothic#227]
Hello @be5invis !

I copied the `config.json` to `config.private.json`. I omitted all fonts, except Sarasa Term and Term Slab, but I got errors about Inter fonts via `npm`. I also want to use Iosevka's `private-build-plans` file for `config.json` or `config.private.json` files, but I am not sure if it will work for `config.json`'s `buildOptions`. Here's my TOML:

```toml
[buildPlans.polyglotto]
family = "Polyglotto"
spacing = "term"
serifs = "sans"

  [buildPlans.polyglotto.variants]
  inherits = "ss20"

    [buildPlans.polyglotto.variants.design]
    paragraph-sign = "low"
    at = "fourfold"
    bar = "natural-slope"
    lig-ltgteq = "slanted"
    ascii-single-quote = "straight"

    [buildPlans.polyglotto.variants.italic]
    number-sign = "slanted"
    lig-ltgteq = "slanted"
    ascii-single-quote = "straight"
    question = "corner-flat-hooked"

    [buildPlans.polyglotto.variants.oblique]
    eszet = "traditional"
    lig-ltgteq = "slanted"
    question = "corner-flat-hooked"

  [buildPlans.polyglotto.ligations]
  inherits = "dlig"
```

Thank you!

Gustavo
